### PR TITLE
UIP executable.

### PR DESCRIPTION
**Pull request by hackrush01**

### CODE REVIEW

**Comment by abh3po** [comment]
@hackrush01  can you move this inside a binaries folder?

**Comment by hackrush01** [comment]
Ok

-Regards
-Amit Tulshyan

**Comment by naveenkumarsangi** [comment]
```
$ ./UIP
Hey this is UIP! you can use it to download images from reddit and also to schedule the setting of these images as your desktop wallpaper. 
Press ctrl-c to exit
UIP will now connect to internet and download images from reddit and unsplash.
You can wait for next wallpaper or skip this wallpaper by just pressing enter.
changing desktop wallpaper to:  /home/nkprince007/.uip/pics/e7iEEH-_yGQ4k_06gYPLn8iWdfrIAxKEtYRCp2EQo4U.jpg
/tmp/_MEIlFVP4Z/uiplib/setWallpaper.py:18: Warning: cannot register existing type 'DConfSettingsBackend'
/tmp/_MEIlFVP4Z/uiplib/setWallpaper.py:18: Warning: g_once_init_leave: assertion 'result != 0' failed

(process:20255): GLib-GIO-WARNING **: Tried to register an extension of the type (null) to extension point gsettings-backend. Expected type is GObject.
^C
Exiting UIP hope you had a nice time :)
```

**Comment by abh3po** [comment]
@nkprince007  is using arch linux this binary works only for debian based systems AFAIK.

**Comment by abh3po** [comment]
@hackrush01 can we just have 1 commit? also can your rename the file to `linux-UIP-ver0.0.3` ?

**Comment by hackrush01** [comment]
Okay

**Pull request merged**
